import { generateId } from "./utils";

export const defaultProfile = {
  id: generateId(),
  name: "My FreeSWITCH",
  domain: "sip.example.com",
  wsUrl: "wss://sip.example.com:7443",
  username: "1001",
  password: "",
  displayName: "User",
  transport: "WSS",
  registerOnStartup: true,
  registrationExpiry: 600,
  stunServer: "stun:stun.l.google.com:19302",
  turnServer: "",
  turnUsername: "",
  turnCredential: "",
  iceTimeout: 5000,
  outboundProxy: "",
};

export const defaultSettings = {
  theme: "dark",
  accentColor: "#3b82f6",
  fontSize: "medium",
  compact: false,
  audioInput: "",
  audioOutput: "",
  ringtone: "classic",
  ringVolume: 0.7,
  autoAnswer: false,
  autoAnswerDelay: 3,
  echoCancellation: true,
  noiseSuppression: true,
  dtmfMode: "rfc2833",
  camera: "",
  videoResolution: "720p",
  selfView: true,
  iceCandidatePolicy: "all",
  srtpMode: "optional",
  sessionTimers: false,
  debugLog: false,
  logLevel: "info",
  sipBackend: "simulated",
};

export const sampleContacts = [
  {
    id: generateId(),
    name: "Alice Johnson",
    sipUri: "sip:alice@example.com",
    phone: "+15551001",
    email: "",
    notes: "",
    color: "#3b82f6",
    speedDial: 1,
  },
  {
    id: generateId(),
    name: "Bob Smith",
    sipUri: "sip:bob@example.com",
    phone: "+15551002",
    email: "",
    notes: "",
    color: "#10b981",
    speedDial: 2,
  },
  {
    id: generateId(),
    name: "Charlie Brown",
    sipUri: "sip:charlie@example.com",
    phone: "+15551003",
    email: "",
    notes: "",
    color: "#8b5cf6",
    speedDial: null,
  },
];
